### ISSUE TITLE
hubot fails to start on node 5.6.0

### ISSUE THREAD

**Issue by bfosberry** [papertrail/papertrail-hubot#3]
[Fri Mar 04 2016 09:06:18 GMT-0600 (CST)] ERROR Unable to load /home/bfosberry/workspace/captain/node_modules/papertrail-hubot/scripts/papertrail: TypeError: Cannot read property 'on' of undefined
  at /home/bfosberry/workspace/captain/node_modules/hubot/node_modules/scoped-http-client/src/index.js:87:14
  at Groups.fetch (/home/bfosberry/workspace/captain/node_modules/papertrail-hubot/scripts/papertrail.coffee:135:7)
  at new Groups (/home/bfosberry/workspace/captain/node_modules/papertrail-hubot/scripts/papertrail.coffee:87:8)
  at module.exports (/home/bfosberry/workspace/captain/node_modules/papertrail-hubot/scripts/papertrail.coffee:209:22)
  at Robot.loadFile (/home/bfosberry/workspace/captain/node_modules/hubot/src/robot.coffee:358:11)
  at /home/bfosberry/workspace/captain/node_modules/papertrail-hubot/index.coffee:8:13
  at FSReqWrap.cb [as oncomplete](fs.js:216:19)

**Comment by cbelizontw** [comment]
The problem is that the script does not exits gracefully when the env variable is not set. I've already created a pull request to fix it:

https://github.com/papertrail/papertrail-hubot/pull/5
